<a href="https://colab.research.google.com/github/KarthikSaravanakumarM56/24ADI006-24BAD056-DL/blob/main/DL_Lab_1a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("M.Karthik Saravanakumar - 24BAD056")

M.Karthik Saravanakumar - 24BAD056

In [2]:
#step 1:Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.20.0

In [3]:
# Step 2: Load the California Housing Dataset
data = fetch_california_housing()
X = data.data
y = data.target

df = pd.DataFrame(X, columns=data.feature_names)
df['MedHouseValue'] = y

print("Dataset shape:", X.shape)
df.head()

Dataset shape: (20640, 8)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseValue
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [4]:
# Step 3: Split into Training and Testing Sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 16512
Testing samples: 4128

In [5]:
# Step 4: Standardize the Features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [6]:
# Step 5: Build the ANN Model
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(16, activation='relu'),
    layers.Dense(1)  # Linear output for regression
])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,201 (12.50 KB)

 Trainable params: 3,201 (12.50 KB)

 Non-trainable params: 0 (0.00 B)

In [7]:
# Step 6: Compile the Model
model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

In [8]:
# Step 7: Train the Model
history = model.fit(
    X_train_scaled, y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    verbose=1
)

Epoch 1/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 1.0562 - mae: 0.6734 - val_loss: 0.4549 - val_mae: 0.4788
Epoch 2/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4020 - mae: 0.4528 - val_loss: 0.3982 - val_mae: 0.4420
Epoch 3/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3736 - mae: 0.4322 - val_loss: 0.3790 - val_mae: 0.4316
Epoch 4/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3462 - mae: 0.4177 - val_loss: 0.3596 - val_mae: 0.4170
Epoch 5/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3293 - mae: 0.4057 - val_loss: 0.3490 - val_mae: 0.4033
Epoch 6/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3192 - mae: 0.3966 - val_loss: 0.4009 - val_mae: 0.4271
Epoch 7/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3227 - mae: 0.3952 - val_loss: 0.3299 - val_mae: 0.4050
Epoch 8/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3114 - mae: 0.3836 - val_loss: 0.3401 - val_mae: 0.3907
Epoch 9/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3003 - mae: 0.3795 - val_loss: 0.3503 - val_mae: 0.4314
Epoch 10/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2967 - mae: 0.3779 - val_loss: 0.3230 - val_mae: 0.3973
Epoch 11/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2927 - mae: 0.3724 - val_loss: 0.3228 - val_mae: 0.3856
Epoch 12/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2874 - mae: 0.3708 - val_loss: 0.3147 - val_mae: 0.3816
Epoch 13/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.2873 - mae: 0.3700 - val_loss: 0.3136 - val_mae: 0.3924
Epoch 14/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.2813 - mae: 0.3667 - val_loss: 0.3142 - val_mae: 0.3860
Epoch 15/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2800 - mae: 0.3657 - val_loss: 0.3194 - val_mae: 0.3983
Epoch 16/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2788 - mae: 0.3639 - val_loss: 0.3099 - val_mae: 0.3834
Epoch 17/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2782 - mae: 0.3643 - val_loss: 0.3103 - val_mae: 0.3816
Epoch 18/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2973 - mae: 0.3659 - val_loss: 0.3273 - val_mae: 0.3820
Epoch 19/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2762 - mae: 0.3628 - val_loss: 0.3054 - val_mae: 0.3799
Epoch 20/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2744 - mae: 0.3605 - val_loss: 0.3036 - val_mae: 0.3749
Epoch 21/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2718 - mae: 0.3579 - val_loss: 0.3040 - val_mae: 0.3706
Epoch 22/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2725 - mae: 0.3591 - val_loss: 0.3032 - val_mae: 0.3757
Epoch 23/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.2675 - mae: 0.3566 - val_loss: 0.3100 - val_mae: 0.3750
Epoch 24/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2654 - mae: 0.3547 - val_loss: 0.2998 - val_mae: 0.3706
Epoch 25/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2694 - mae: 0.3568 - val_loss: 0.3024 - val_mae: 0.3771
Epoch 26/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.2684 - mae: 0.3553 - val_loss: 0.3149 - val_mae: 0.3707
Epoch 27/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2687 - mae: 0.3549 - val_loss: 0.3112 - val_mae: 0.3784
Epoch 28/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2676 - mae: 0.3544 - val_loss: 0.3008 - val_mae: 0.3776
Epoch 29/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2630 - mae: 0.3514 - val_loss: 0.2994 - val_mae: 0.3809
Epoch 30/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2610 - mae: 0.3505 - val_loss: 0.2942 - val_mae: 0.3717
Epoch 31/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2606 - mae: 0.3500 - val_loss: 0.2952 - val_mae: 0.3735
Epoch 32/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2597 - mae: 0.3491 - val_loss: 0.2986 - val_mae: 0.3791
Epoch 33/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2602 - mae: 0.3506 - val_loss: 0.2944 - val_mae: 0.3643
Epoch 34/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2567 - mae: 0.3478 - val_loss: 0.2977 - val_mae: 0.3665
Epoch 35/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2590 - mae: 0.3484 - val_loss: 0.3110 - val_mae: 0.3713
Epoch 36/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2562 - mae: 0.3470 - val_loss: 0.3113 - val_mae: 0.3821
Epoch 37/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2562 - mae: 0.3465 - val_loss: 0.2993 - val_mae: 0.3711
Epoch 38/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2529 - mae: 0.3437 - val_loss: 0.3007 - val_mae: 0.3701
Epoch 39/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2549 - mae: 0.3453 - val_loss: 0.2977 - val_mae: 0.3759
Epoch 40/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2536 - mae: 0.3446 - val_loss: 0.3005 - val_mae: 0.3634
Epoch 41/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2525 - mae: 0.3444 - val_loss: 0.2909 - val_mae: 0.3730
Epoch 42/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2514 - mae: 0.3430 - val_loss: 0.3004 - val_mae: 0.3723
Epoch 43/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2500 - mae: 0.3421 - val_loss: 0.2960 - val_mae: 0.3721
Epoch 44/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2496 - mae: 0.3419 - val_loss: 0.3037 - val_mae: 0.3636
Epoch 45/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2488 - mae: 0.3405 - val_loss: 0.2961 - val_mae: 0.3708
Epoch 46/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2488 - mae: 0.3415 - val_loss: 0.2890 - val_mae: 0.3649
Epoch 47/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2468 - mae: 0.3398 - val_loss: 0.2916 - val_mae: 0.3609
Epoch 48/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2469 - mae: 0.3397 - val_loss: 0.3149 - val_mae: 0.3717
Epoch 49/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.2444 - mae: 0.3389 - val_loss: 0.2970 - val_mae: 0.3640
Epoch 50/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2451 - mae: 0.3387 - val_loss: 0.2909 - val_mae: 0.3595
Epoch 51/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2535 - mae: 0.3419 - val_loss: 0.2933 - val_mae: 0.3641
Epoch 52/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2424 - mae: 0.3373 - val_loss: 0.2925 - val_mae: 0.3603
Epoch 53/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.2438 - mae: 0.3390 - val_loss: 0.3027 - val_mae: 0.3847
Epoch 54/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2430 - mae: 0.3380 - val_loss: 0.2975 - val_mae: 0.3735
Epoch 55/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2394 - mae: 0.3339 - val_loss: 0.2931 - val_mae: 0.3672
Epoch 56/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2392 - mae: 0.3343 - val_loss: 0.2967 - val_mae: 0.3650
Epoch 57/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2400 - mae: 0.3348 - val_loss: 0.2941 - val_mae: 0.3598
Epoch 58/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2387 - mae: 0.3349 - val_loss: 0.2909 - val_mae: 0.3572
Epoch 59/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2383 - mae: 0.3334 - val_loss: 0.2886 - val_mae: 0.3689
Epoch 60/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2381 - mae: 0.3343 - val_loss: 0.2852 - val_mae: 0.3599
Epoch 61/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2371 - mae: 0.3332 - val_loss: 0.2905 - val_mae: 0.3554
Epoch 62/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2363 - mae: 0.3320 - val_loss: 0.2922 - val_mae: 0.3678
Epoch 63/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2358 - mae: 0.3314 - val_loss: 0.2911 - val_mae: 0.3627
Epoch 64/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2346 - mae: 0.3314 - val_loss: 0.2910 - val_mae: 0.3631
Epoch 65/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2351 - mae: 0.3313 - val_loss: 0.2902 - val_mae: 0.3649
Epoch 66/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2328 - mae: 0.3301 - val_loss: 0.2873 - val_mae: 0.3593
Epoch 67/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.2337 - mae: 0.3307 - val_loss: 0.2976 - val_mae: 0.3654
Epoch 68/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2313 - mae: 0.3298 - val_loss: 0.3000 - val_mae: 0.3773
Epoch 69/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2319 - mae: 0.3300 - val_loss: 0.3025 - val_mae: 0.3775
Epoch 70/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2320 - mae: 0.3294 - val_loss: 0.3151 - val_mae: 0.3942
Epoch 71/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2316 - mae: 0.3294 - val_loss: 0.2921 - val_mae: 0.3667
Epoch 72/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2308 - mae: 0.3280 - val_loss: 0.2981 - val_mae: 0.3781
Epoch 73/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2290 - mae: 0.3278 - val_loss: 0.2934 - val_mae: 0.3691
Epoch 74/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2317 - mae: 0.3286 - val_loss: 0.2899 - val_mae: 0.3753
Epoch 75/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2277 - mae: 0.3276 - val_loss: 0.3135 - val_mae: 0.3725
Epoch 76/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2263 - mae: 0.3251 - val_loss: 0.2876 - val_mae: 0.3637
Epoch 77/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2273 - mae: 0.3275 - val_loss: 0.2843 - val_mae: 0.3598
Epoch 78/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2277 - mae: 0.3282 - val_loss: 0.2959 - val_mae: 0.3648
Epoch 79/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2236 - mae: 0.3245 - val_loss: 0.3012 - val_mae: 0.3717
Epoch 80/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.2252 - mae: 0.3264 - val_loss: 0.2840 - val_mae: 0.3572
Epoch 81/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2250 - mae: 0.3259 - val_loss: 0.2889 - val_mae: 0.3600
Epoch 82/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2233 - mae: 0.3240 - val_loss: 0.2843 - val_mae: 0.3629
Epoch 83/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2237 - mae: 0.3247 - val_loss: 0.3075 - val_mae: 0.3795
Epoch 84/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2257 - mae: 0.3260 - val_loss: 0.2812 - val_mae: 0.3551
Epoch 85/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2209 - mae: 0.3233 - val_loss: 0.2812 - val_mae: 0.3563
Epoch 86/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2225 - mae: 0.3239 - val_loss: 0.2830 - val_mae: 0.3596
Epoch 87/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2218 - mae: 0.3234 - val_loss: 0.2829 - val_mae: 0.3589
Epoch 88/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2211 - mae: 0.3223 - val_loss: 0.2811 - val_mae: 0.3551
Epoch 89/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2194 - mae: 0.3218 - val_loss: 0.2841 - val_mae: 0.3550
Epoch 90/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2188 - mae: 0.3211 - val_loss: 0.2851 - val_mae: 0.3661
Epoch 91/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2190 - mae: 0.3211 - val_loss: 0.2852 - val_mae: 0.3602
Epoch 92/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2216 - mae: 0.3227 - val_loss: 0.2856 - val_mae: 0.3603
Epoch 93/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2200 - mae: 0.3222 - val_loss: 0.2902 - val_mae: 0.3687
Epoch 94/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2195 - mae: 0.3221 - val_loss: 0.2838 - val_mae: 0.3583
Epoch 95/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2169 - mae: 0.3194 - val_loss: 0.2994 - val_mae: 0.3803
Epoch 96/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2181 - mae: 0.3217 - val_loss: 0.2782 - val_mae: 0.3543
Epoch 97/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2176 - mae: 0.3200 - val_loss: 0.2785 - val_mae: 0.3513
Epoch 98/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2161 - mae: 0.3191 - val_loss: 0.2857 - val_mae: 0.3676
Epoch 99/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2152 - mae: 0.3172 - val_loss: 0.2847 - val_mae: 0.3610
Epoch 100/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2168 - mae: 0.3195 - val_loss: 0.2846 - val_mae: 0.3597

In [9]:
# Step 8: Predict House Prices
y_pred = model.predict(X_test_scaled).flatten()

comparison_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
comparison_df.head(10)

129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

    Actual  Predicted
0  0.47700   0.396524
1  0.45800   0.756813
2  5.00001   5.146418
3  2.18600   2.441366
4  2.78000   2.860358
5  1.58700   1.419657
6  1.98200   2.332985
7  1.57500   1.557018
8  3.40000   2.483640
9  4.46600   4.829980

In [10]:
# Step 9: Evaluate the Model (MSE, MAE, RMSE)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")

Mean Squared Error (MSE): 0.2761
Mean Absolute Error (MAE): 0.3514
Root Mean Squared Error (RMSE): 0.5255